services:
  redis:
    image: redis
    container_name: imagepipe-redis
    ports:
      - "6379:6379"

  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    container_name: imagepipe-gateway
    ports:
      - "5000:5000"
    command: python gateway/app.py
    depends_on:
      - redis
    volumes:
      - ./uploads:/app/uploads
      - ./instance:/app/instance
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FLASK_APP=${FLASK_APP}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_PUBLIC_HOST=${MINIO_PUBLIC_HOST}
      - REACT_APP_API_URL=${REACT_APP_API_URL}

  worker-convert:
    build:
      context: .
      dockerfile: ./services/convert/Dockerfile
    container_name: worker-coonvert
    command: celery -A services.convert.convert_worker worker -n convert@%h -Q convert_queue --loglevel=info --pool=solo
    depends_on:
      - redis
    volumes:
      - ./uploads:/app/uploads
      - ./instance:/app/instance
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FLASK_APP=${FLASK_APP}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_PUBLIC_HOST=${MINIO_PUBLIC_HOST}
      - REACT_APP_API_URL=${REACT_APP_API_URL}

  worker-filter:
    build:
      context: .
      dockerfile: ./services/filter/Dockerfile
    container_name: worker-filter
    command: celery -A services.filter.filter_worker worker -n filter@%h -Q filter_queue --loglevel=info --pool=solo
    depends_on:
      - redis
    volumes:
      - ./uploads:/app/uploads
      - ./instance:/app/instance
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FLASK_APP=${FLASK_APP}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_PUBLIC_HOST=${MINIO_PUBLIC_HOST}
      - REACT_APP_API_URL=${REACT_APP_API_URL}

  worker-ocr:
    build:
      context: .
      dockerfile: ./services/ocr/Dockerfile
    container_name: worker-ocr
    command: celery -A services.ocr.ocr_worker worker -n ocr@%h -Q ocr_queue --loglevel=info --pool=solo
    depends_on:
      - redis
    volumes:
      - ./uploads:/app/uploads
      - ./instance:/app/instance
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FLASK_APP=${FLASK_APP}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_PUBLIC_HOST=${MINIO_PUBLIC_HOST}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
  
  worker-cleaner:
    build:
      context: .
      dockerfile: ./services/cleaner/Dockerfile
    container_name: worker-cleaner
    command: celery -A services.cleaner.cleaner_worker worker -B -n cleaner@%h -Q cleaner_queue --loglevel=info --pool=solo
    depends_on:
      - redis
      - minio
    volumes:
      - ./uploads:/app/uploads
      - ./instance:/app/instance
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FLASK_APP=${FLASK_APP}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_PUBLIC_HOST=${MINIO_PUBLIC_HOST}
      - REACT_APP_API_URL=${REACT_APP_API_URL}

  minio:
    image: minio/minio
    container_name: imagepipe-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"

  ui:
    build:
      context: ./imagepipe-ui
      dockerfile: Dockerfile
    container_name: imagepipe-ui
    # depends_on:
    #   - gateway
    # ports:
    #   - "3000:3000" # UI port for development
    volumes:
      - ./imagepipe-ui/nginx.conf:/etc/nginx/nginx.conf:ro
    # stdin_open: true
    # tty: true

  nginx:
    image: nginx:latest
    container_name: imagepipe-nginx
    ports:
      - "80:80"
    volumes:
      - ./imagepipe-ui/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./imagepipe-ui/build:/usr/share/nginx/html
    depends_on:
      - ui
      - gateway

  postgres:
    image: postgres:15
    container_name: imagepipe-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data