apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: imagepipe-gateway  
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_ENV
              value: "development"
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: imagepipe-secret
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: imagepipe-secret
                  key: MINIO_ROOT_PASSWORD
            - name: S3_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: imagepipe-secret
                  key: S3_ENDPOINT_URL
            - name: MINIO_PUBLIC_HOST
              valueFrom:
                secretKeyRef:
                  name: imagepipe-secret
                  key: MINIO_PUBLIC_HOST
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: imagepipe-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: imagepipe-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: imagepipe-secret
                  key: POSTGRES_DB
            - name: REACT_APP_API_URL
              valueFrom:
                secretKeyRef:
                  name: imagepipe-secret
                  key: REACT_APP_API_URL
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: uploads
          hostPath:
            path: /app/uploads
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000 # http://localhost:30000
