apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-filter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-filter
  template:
    metadata:
      labels:
        app: worker-filter
    spec:
      containers:
      - name: worker-filter
        image: imagepipe-worker-filter
        imagePullPolicy: Never
        command: ["celery"]
        args: ["-A", "services.filter.filter_worker", "worker", "-n", "filter@%h", "-Q", "filter_queue", "--loglevel=info", "--pool=solo"]
        env:
          - name: MINIO_ROOT_USER
            valueFrom:
              secretKeyRef:
                name: imagepipe-secret
                key: MINIO_ROOT_USER
          - name: MINIO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: imagepipe-secret
                key: MINIO_ROOT_PASSWORD
          - name: S3_ENDPOINT_URL
            valueFrom:
              secretKeyRef:
                name: imagepipe-secret
                key: S3_ENDPOINT_URL
          - name: MINIO_PUBLIC_HOST
            valueFrom:
              secretKeyRef:
                name: imagepipe-secret
                key: MINIO_PUBLIC_HOST
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: imagepipe-secret
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: imagepipe-secret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: imagepipe-secret
                key: POSTGRES_DB
          - name: REACT_APP_API_URL
            valueFrom:
              secretKeyRef:
                name: imagepipe-secret
                key: REACT_APP_API_URL
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
        resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
      - name: uploads
        hostPath:
          path: /app/uploads
          type: DirectoryOrCreate
