"""init

Revision ID: e226662b9c0b
Revises: 
Create Date: 2025-05-13 14:33:18.493497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e226662b9c0b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_records',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=True),
    sa.Column('process_type', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.String(length=512), nullable=True),
    sa.Column('result_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_records')
    # ### end Alembic commands ###
